import toastr from 'toastr'
Template.adminInviteUser.helpers({
	isAdmin: function() {
		return RocketChat.authz.hasRole(Meteor.userId(), 'admin');
	},
	inviteEmails: function() {
		return Template.instance().inviteEmails.get();
	}
});

Template.adminInviteUser.events({
	'click .send': function(e, instance) {
		var emails, rfcMailPattern, validEmails;
		emails = $('#inviteEmails').val().split(/[\s,;]/);
		rfcMailPattern = /^[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/;
		validEmails = _.compact(_.map(emails, function(email) {
			if (rfcMailPattern.test(email)) {
				return email;
			}
		}));
		if (validEmails.length) {
			return Meteor.call('sendInvitationEmail', validEmails, function(error, result) {
				if (result) {
					instance.clearForm();
					instance.inviteEmails.set(validEmails);
				}
				if (error) {
					return handleError(error);
				}
			});
		} else {
			return toastr.error(t('Send_invitation_email_error'));
		}
	},
	'click .cancel': function(e, instance) {
		instance.clearForm();
		instance.inviteEmails.set([]);
		return RocketChat.TabBar.closeFlex();
	}
});

Template.adminInviteUser.onCreated(function() {
	this.inviteEmails = new ReactiveVar([]);
	return this.clearForm = function() {
		return $('#inviteEmails').val('');
	};
});

// ---
// generated by coffee-script 1.9.2
