Template.adminUserChannels.helpers({
	type: function() {
		if (this.t === 'd') {
			return 'at';
		} else if (this.t === 'p') {
			return 'lock';
		} else {
			return 'hash';
		}
	},
	route: function() {
		switch (this.t) {
			case 'd':
				return FlowRouter.path('direct', {
					username: this.name
				});
			case 'p':
				return FlowRouter.path('group', {
					name: this.name
				});
			case 'c':
				return FlowRouter.path('channel', {
					name: this.name
				});
		}
	}
});

// ---
// generated by coffee-script 1.9.2
